# Generated by Django 3.2.9 on 2022-01-12 15:06

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50, verbose_name='Categorie naam')),
                ('icon', models.CharField(default='question-mark', max_length=50, verbose_name='Naam van het bijpassende icon (icons8.com)')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorieën',
            },
        ),
        migrations.CreateModel(
            name='Klant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telnr', models.CharField(max_length=12, verbose_name='Telefoon nummer')),
            ],
            options={
                'verbose_name': 'Klant',
                'verbose_name_plural': 'Klanten',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50, verbose_name='Product naam')),
                ('snijdbaar', models.BooleanField(default=False, verbose_name='Snijdbaar')),
                ('hoeveelheid', models.IntegerField(default=1, verbose_name='Te bestellen per (bv. 1 st./200 gr.)')),
                ('eenheid', models.CharField(choices=[('st.', 'st.'), ('gr.', 'gr.')], default='st.', max_length=3, verbose_name='Eenheid')),
                ('state', models.CharField(choices=[('niet_gestart', 'Niet Gestart'), ('bezig', 'Bezig'), ('probleem', 'Probleem'), ('voltooid', 'Voltooid')], default='niet_gestart', max_length=20)),
                ('foto', models.ImageField(default='product_fotos/default_product.jpg', upload_to='product_fotos', verbose_name='Foto van product')),
                ('categorie', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='shopApp.categorie', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Producten',
                'ordering': ['state'],
            },
        ),
        migrations.CreateModel(
            name='Bestelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besteltijd', models.DateTimeField(auto_now_add=True)),
                ('producten', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('dag_ophalen', models.DateField(default=datetime.date(2022, 1, 1), verbose_name='Dag van ophalen')),
                ('klant', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='shopApp.klant', verbose_name='Geplaatst door')),
            ],
            options={
                'verbose_name': 'Bestelling',
                'verbose_name_plural': 'Bestellingen',
                'ordering': ['-besteltijd'],
            },
        ),
    ]
