# Generated by Django 3.2.9 on 2022-01-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='zichtbaar',
            field=models.BooleanField(default=True, verbose_name='Zichtbaar'),
        ),
        migrations.AddField(
            model_name='product',
            name='zichtbaar',
            field=models.BooleanField(default=True, verbose_name='Zichtbaar'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='icon',
            field=models.CharField(default='question-mark', max_length=50, verbose_name='Naam van het bijpassende icon (icons8.com -> iOS filled type)'),
        ),
    ]
