# Generated by Django 3.2.9 on 2022-01-12 16:15

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_auto_20220112_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('foto', '550x550', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
